# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f57d157215dbce3f5cbaeef425fd612902adcb825988819494a71d7f806b25bff31a5d1f2a69b16143984de260937b821a548012c6ce8e79427b6eff8ba46060

test:
  secret_key_base: 80f0d9c8f6514d704b00013ffde90f77d687d643c13e7ad1150c115747e0bac2504ed0d770871290b686168933ac31472269277173c2b996c2248d5848c827f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
